# Generated by Django 4.2.1 on 2023-06-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0003_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookings',
        ),
    ]
